JSilverCsv/Controllers/CampaignsController.cs
using JSilverCsv.Models;
using JSilverCsv.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace JSilverCsv.Controllers
{
    [Authorize]
    public class CampaignsController : Controller
    {
        ApplicationDbContext ctx;
        public CampaignsController()
        {
            ctx = new Models.ApplicationDbContext();
        }
        // GET: Campaigns
        public ActionResult Index()
        {
            var allDataFIles = ctx.DataFiles.ToList();
            return View(allDataFIles);
        }
        public ActionResult Upload(HttpPostedFileBase file)
        {
            // save input file to disk
            if (file == null || file.ContentLength < 1)
                return new HttpStatusCodeResult(500, "File content is empty!");

            try
            {
                Stream stream = file.InputStream;
                using (var reader = new StreamReader(stream))
                {
                    string dataString = reader.ReadToEnd().Trim();
                    var dataArray = dataString.Split('\n');
                    int numberOfRecords = dataArray.Count() - 1;

                    // now upload file
                    string inputPath = "~/InputFiles/";
                    //var extension = Path.GetExtension(file.FileName);
                    //string ordinaryFileName = Path.GetFileName(file.FileName);
                    //string myFileName = ordinaryFileName + "_" + Guid.NewGuid() + extension;

                    var path = Path.Combine(Server.MapPath(inputPath), file.FileName);
                    file.SaveAs(path);

                    return Json(new { success = true, qty = numberOfRecords, path = inputPath + file.FileName });
                }


            }
            catch (Exception ex)
            {
                return Json(new { success = false, msg = "An error occured while uploading file!" });
            }
        }
        public ActionResult Create()
        {
            
            Random rnd = new Random();
            //int x1 = rnd.Next(1,25);
            //int x2 = rnd.Next(1, 25);
            //int rem = 100 - (x1 + x2);
            //int x3 = rnd.Next(rem / 3);
            //int x4 = rem - x3;
            int x1 = rnd.Next(1, 10);
            int x2 = rnd.Next(1, 10);
            int x3 = rnd.Next(1, 10);
            int x4 = rnd.Next(1, 10);
            int sum = x1 + x2 + x3 + x4;
            x1 = x1 * 100 / sum;
            x2 = x2 * 100 / sum;
            x3 = x3 * 100 / sum;
            x4 = x4 * 100 / sum;
            CreateCampaignViewModel model = new ViewModels.CreateCampaignViewModel()
            {
                ColE0To30 = x1,
                ColE31To60 = x2,
                ColE61To90 = x3,
                ColE91Plus = x4
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(CreateCampaignViewModel model)
        {
            if (ModelState.IsValid)
            {
                var outputFileBuilder = new StringBuilder();
                using (var reader = new StreamReader(Server.MapPath(model.InputFilePath)))
                {
                    #region verify input file and form data
                    // get the actual csv data as string and then store in array
                    string dataString = reader.ReadToEnd().Trim();
                    var dataArray = dataString.Split('\n');

                    // verify input data
                    int numberOfRecords = model.Qty;
                    // colA <= colB <= colC <= colD <= number of records
                    if (model.ColA > numberOfRecords || model.ColB > numberOfRecords)
                    {
                        ModelState.AddModelError("", "Values of colA to colD can not be greater than the number of records in file");
                        return View(model);
                    }
                    if (model.ColE0To30 + model.ColE31To60 + model.ColE61To90 + model.ColE91Plus > numberOfRecords)
                    {
                        ModelState.AddModelError("", "Column E records can not be more than the number of records in file");
                        return View(model);
                    }
                    #endregion

                    #region Get header and layout type
                    // Take the header => the first row
                    var firstRowHeader = dataArray[0].Trim();   // trim any new line at the end


                    if (firstRowHeader.Trim().EndsWith(","))
                    {
                        firstRowHeader = firstRowHeader.Trim().TrimEnd(',');
                    }
                    int numberOfColumns = firstRowHeader.Split(',').Count();

                    // Randomize the data skipping the first row
                    Random rnd = new Random();
                    var randomizedArray = dataArray.Skip(1).Where(d => !String.IsNullOrWhiteSpace(d.Replace(',', ' '))).OrderBy(x => rnd.Next()).ToArray();


                    int layoutType = 0; bool extraColumnsAlreadyAppended = false;
                    if (!extraColumnsAlreadyAppended)
                    {
                        // append extra columns to header
                        firstRowHeader += ",Open,Click,Bounced,Optout,Filler1";
                    }
                    outputFileBuilder.AppendLine(firstRowHeader);
                    #endregion

                    #region process data
                    int countC = 0; int countD = 0;
                    // loop through the data and append X where neccessary
                    for (int i = 0; i < randomizedArray.Length; i++)
                    {
                        string row = randomizedArray[i];
                        var rowColumns = row.Split(',');
                        string colA = model.ColA > i ? "Y" : "";
                        string colB = model.ColB > i ? "Y" : "";
                        string colC = "";
                        if(colA == "" && colB == "" && countC < model.ColC)
                        {
                            colC = "Y";
                            countC++;
                        }
                        string colD = "";
                        if (colA == "" && colB == "" && colC == "" && countD < model.ColD)
                        {
                            colD = "Y";
                            countD++;
                        }

                        string colE = string.Empty;
                        if (i < model.ColE0To30)
                        {
                            colE = "0 - 30";
                        }
                        else if (i < (model.ColE0To30 + model.ColE31To60))
                        {
                            colE = "31 - 60";
                        }
                        else if (i < (model.ColE0To30 + model.ColE31To60 + model.ColE61To90))
                        {
                            colE = "61 - 90";
                        }
                        else colE = "91+";

                        // append data to row
                        outputFileBuilder.AppendLine(String.Join(",", row.Trim().TrimEnd(',').Split(',').Take(numberOfColumns).ToArray()) + $",{colA},{colB},{colC},{colD},{colE}");
                    }
                    #endregion

                    CreateNeccessaryFolders();


                    string fileName = Path.GetFileNameWithoutExtension(model.InputFilePath);
                    // save output file
                    string outputPath = "~/OutputFiles/" + fileName + "_Match_QTY"+model.Qty + ".csv";
                    // .AppendAllText does not autoreplace so check if exist then delete
                    RemoveFileFromDisk(outputPath);
                    System.IO.File.AppendAllText(Server.MapPath(outputPath), outputFileBuilder.ToString());

                    DataFile dataFile = new DataFile
                    {
                        ColA = model.ColA,
                        ColB = model.ColB,
                        ColC = model.ColC,
                        ColD = model.ColD,
                        ColE0To30 = model.ColE0To30,
                        ColE31To60 = model.ColE31To60,
                        ColE61To90 = model.ColE61To90,
                        ColE91Plus = model.ColE91Plus,
                        CampaignName = model.Name,
                        InputFileUri = model.InputFilePath,
                        OutputFileUri = outputPath,
                        NumberOfRecords = numberOfRecords,
                        OrderId = model.OrderId
                    };
                    ctx.DataFiles.Add(dataFile);
                    ctx.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateOld(CreateCampaignViewModel model)
        {
            if (ModelState.IsValid)
            {
                var outputFileBuilder = new StringBuilder();
                string fileName = Path.GetFileNameWithoutExtension(model.CsvInputFile.FileName);

                Stream stream = model.CsvInputFile.InputStream;
                using (var reader = new StreamReader(stream))
                {
                    #region verify input file and form data
                    // get the actual csv data as string and then store in array
                    string dataString = reader.ReadToEnd().Trim();
                    var dataArray = dataString.Split('\n');

                    // verify input data
                    int numberOfRecords = dataArray.Count() - 1; // the first record is the header
                    // colA <= colB <= colC <= colD <= number of records

JSilverCsv/Views/Campaigns/Create.cshtml
@model JSilverCsv.ViewModels.CreateCampaignViewModel
@{
    ViewBag.Title = "Create";
}


<style>
    table {
        width: 100%;
    }

    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    table#t01 tr:nth-child(even) {
        background-color: #eee;
    }

    table#t01 tr:nth-child(odd) {
        background-color: #fff;
    }

    table#t01 th {
        background-color: black;
        color: white;
    }
</style>


<h2>Create Campaign</h2>
<br>

@using (Html.BeginForm("Create", "Campaigns", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <input type="hidden" id="InputFilePath" name="InputFilePath" />
    <input type="hidden" id="Qty" name="Qty" />

    <input type="file" name="CsvInputFile" id="CsvInputFile" accept=".csv"/>
    <input type="button" id="btnUpload" value="Upload File" class="btn btn-info btn-lg" onclick="upload()"/>
    <div id="loadingDiv" style="display:none">
        <h4 class="text-danger" >Uploading...please wait!</h4>
    </div>

    @Html.ValidationMessageFor(model => model.CsvInputFile, "", new { @class = "text-danger" })

    <div id="tableDiv" style="display:none">
        <table id="t01">
            <tr>
                <td>QTY</td>
                <td><label id="qtyLablel">0</label></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Order #</td>
                <td>@Html.EditorFor(m => m.OrderId)</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Campaign Name</td>
                <td>@Html.EditorFor(m => m.Name)</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
         
            <tr>
                <td>Column A</td>
                <td>@Html.EditorFor(m => m.ColA)</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Column B</td>
                <td>@Html.EditorFor(m => m.ColB)</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Column C</td>
                <td>@Html.EditorFor(m => m.ColC)</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Column D</td>
                <td>@Html.EditorFor(m => m.ColD)</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Column E</td>
                <td>0 - 30</td>
                <td>31 - 60</td>
                <td>61 - 90</td>
                <td>91+</td>
            </tr>
            <tr>
                <td>Enter QTY for col E </td>
                <td>@Html.TextBoxFor(m => m.ColE0To30, new {@readonly=true })</td>
                <td>@Html.TextBoxFor(m => m.ColE31To60, new { @readonly = true })</td>
                <td>@Html.TextBoxFor(m => m.ColE61To90, new { @readonly = true })</td>
                <td>@Html.TextBoxFor(m => m.ColE91Plus, new { @readonly = true })</td>
            </tr>
        </table>

        <hr />
        <input type="submit" class="btn btn-primary btn-lg" value="Process file" />
    </div>

   

   
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    //window.onload = function () {
    //    $("#tableDiv").hide();
    //}


    function upload() {
        
        $("#btnUpload").attr("disabled", true);
        if (!confirm("Upload selected file")) return;
        var url = "/Campaigns/Upload";
        // var form = $('form');
        var doc = document.getElementById("CsvInputFile").files[0];
        if (doc) {
            var formData = new FormData($('form').get(0));
            formData.append("file", doc);

            $.ajax({
                type: "POST",
                url: url,
                data: formData,
                contentType: false,
                processData: false,
                beforeSend: function () {
                    showLoadingDiv();
                },
                complete: function () {
                    hideLoadingDiv();
                },
                error: function (e) {
                    if (e) {
                        alert(e.statusText);
                    }
                    else {
                        alert(e.statusText);
                    }

                },
                success: function (response) {
                    if (response.success) {
                        alert("Csv file Uploaded!");
                        $("#InputFilePath").val(response.path);
                        $("#Qty").val(response.qty);
                        $("#tableDiv").show();
                        $("#qtyLablel").text(response.qty);
                        
                        updateFilerValues(response.qty)
                    }
                    else {
                        alert(response.msg);
                    }
                   
                }
            });
        }
        else {
            alert("Please select a csv file")
        }
    }

    function updateFilerValues(qty) {
        $("#ColE0To30").val(Math.floor($("#ColE0To30").val() * qty / 100));
        $("#ColE31To60").val(Math.floor($("#ColE31To60").val() * qty / 100));
        $("#ColE61To90").val(Math.floor($("#ColE61To90").val() * qty / 100));
        $("#ColE91Plus").val(qty - (+$("#ColE0To30").val() + +$("#ColE31To60").val() + +$("#ColE61To90").val()));  // the plus to convert str to num first: https://stackoverflow.com/a/8976659/7162741
    }
    function showLoadingDiv() {
        $("#loadingDiv").show();
    }
    function hideLoadingDiv() {
        $("#loadingDiv").hide();
    }
</script>

JSilverCsv/Views/Campaigns/Details.cshtml
@model JSilverCsv.Models.DataFile

@{
    ViewBag.Title = "Details";
}


<div>
    
   
    <h2>Data file Details</h2>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <h3>Qty (In file)</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.NumberOfRecords</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>Order ID</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.OrderId</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>Name</h3>
        </div>
        <div class="col-md-6">
           <h3>@Model.CampaignName</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <h3>Column A</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColA</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>Column B</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColB</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>Column C</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColC</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>Column D</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColD</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>0 - 30</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColE0To30</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>31 - 60</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColE31To60</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>61 - 90</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColE61To90</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h3>91+</h3>
        </div>
        <div class="col-md-6">
            <h3>@Model.ColE91Plus</h3>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-2">
            <h4>Input file</h4>
        </div>
        <div class="col-md-6">
            <h4>@Html.ActionLink("Download", "Dli", new { fileName = Model.InputFileUri })</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <h4>Output file</h4>
        </div>
        <div class="col-md-6">
            @*<h4>@Html.ActionLink("Download", "Dlo", new { fileName = Model.OutputFileUri })</h4>*@
            <h4><a href="#" onclick='downloadOutputFile("@Path.GetFileName(Model.OutputFileUri)")'>Download</a> </h4>
        </div>
    </div>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<script type="text/javascript">
   
    function downloadOutputFile(originaFileName) {
        debugger;
        var dn = originaFileName;
        dn = prompt("Enter desired fileName:", originaFileName);
        if (!dn) {
            alert("Please specify a valid name");
        } else {
            // location.href = "/Campaigns/Dlo?originalFileName="+originaFileName+"&downloadFileName="+dn;
            var uri = "/Campaigns/Dlo?originalFileName="+originaFileName+"&downloadFileName="+dn;
            downloadURI(uri);
        }
    }

    function downloadURI(uri) {
        var link = document.createElement("a");
        //link.download = "Test.csv";
        link.href = uri;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        delete link;
    }
</script>

JSilverCsv/Views/Campaigns/Edit.cshtml
@model JSilverCsv.ViewModels.EditCampaignViewModel
@{
    ViewBag.Title = "Edit";
}


<style>
    table {
        width: 100%;
    }

    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    table#t01 tr:nth-child(even) {
        background-color: #eee;
    }

    table#t01 tr:nth-child(odd) {
        background-color: #fff;
    }

    table#t01 th {
        background-color: black;
        color: white;
    }
</style>


<h2>Edit Campaign</h2>
<br>

@using (Html.BeginForm("Edit", "Campaigns", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

   @Html.HiddenFor(m => m.ID)
    @Html.HiddenFor(m => m.InputFilePath)
    @Html.HiddenFor(m => m.OutputFilePath)

 
    <table id="t01">
        <tr>
            <td>QTY</td>
            <td><label id="qtyLablel">@Model.Qty</label></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <td>Order #</td>
            <td>@Html.EditorFor(m => m.OrderId)</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Campaign</td>
            <td>@Html.EditorFor(m => m.Name)</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Column A</td>
            <td>@Html.EditorFor(m => m.ColA)</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Column B</td>
            <td>@Html.EditorFor(m => m.ColB)</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Column C</td>
            <td>@Html.EditorFor(m => m.ColC)</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Column D</td>
            <td>@Html.EditorFor(m => m.ColD)</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Column E</td>
            <td>0 - 30</td>
            <td>31 - 60</td>
            <td>61 - 90</td>
            <td>91+</td>
        </tr>
        <tr>
            <td>Enter QTY for col E </td>
            <td>@Html.TextBoxFor(m => m.ColE0To30, new { @readonly = true })</td>
            <td>@Html.TextBoxFor(m => m.ColE31To60, new { @readonly = true })</td>
            <td>@Html.TextBoxFor(m => m.ColE61To90, new { @readonly = true })</td>
            <td>@Html.TextBoxFor(m => m.ColE91Plus, new { @readonly = true })</td>
        </tr>
    </table>

    <hr />
    <input type="submit" class="btn btn-primary btn-lg" value="Update" />
}

JSilverCsv/Views/Campaigns/Index.cshtml
@model IEnumerable<JSilverCsv.Models.DataFile>
@{
    ViewBag.Title = "Index";
}


<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<h2>List of available data files</h2> @Html.ActionLink("Create New", "Create", null, new { @class = "pull-right" })
<br>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Campaign Name</th>
            <th>QTY (In file)</th>
            <th>Order #</th>
            <th>Col A</th>
            <th>Col B</th>
            <th>Col C</th>
            <th>Col D</th>
            <th>Original File</th>
            <th>Processed File</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var data in Model)
        {
            <tr>
                <td>@data.ID</td>
                <td>@data.CampaignName</td>
                <td>@data.NumberOfRecords</td>
                <td>@data.OrderId</td>
                <td>@data.ColA</td>
                <td>@data.ColB</td>
                <td>@data.ColC</td>
                <td>@data.ColD</td>
                <td>@Html.ActionLink("Download", "Dli", new { fileName = data.InputFileUri })</td>
                <td><a href="#" onclick='downloadOutputFile("@Path.GetFileName(data.OutputFileUri)")'>Download output</a> </td>
                <td>@Html.ActionLink("View Details", "Details", new { id = data.ID })</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = data.ID })</td>

                <td><a href="#" onclick="Delete(@data.ID)">Delete</a></td>


            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    function Delete(id){
        if(confirm("Confirm delete???")){
            location.href = "/Campaigns/Delete?id="+id;
        }
    }
    function downloadOutputFile(originaFileName) {
        debugger;
        var dn = originaFileName;
        dn = prompt("Enter desired fileName:", originaFileName);
        if (!dn) {
            alert("Please specify a valid name");
        } else {
            // location.href = "/Campaigns/Dlo?originalFileName="+originaFileName+"&downloadFileName="+dn;
            var uri = "/Campaigns/Dlo?originalFileName="+originaFileName+"&downloadFileName="+dn;
            downloadURI(uri);
        }
    }

    function downloadURI(uri) {
        var link = document.createElement("a");
        //link.download = "Test.csv";
        link.href = uri;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        delete link;
    }
</script>